[package]
name = "gtt-bindgen-cli"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "gtt-bindgen"
path = "src/main.rs"

[dependencies]
cargo_metadata = "0.15"
anyhow = "1"
camino = "1"
uniffi_bindgen = { version = "0.28", features = ["cargo-metadata"] }
uniffi = { version = "0.28", features = ["bindgen", "cargo-metadata"] }